### ISSUE TITLE
get error with library

### ISSUE THREAD

**Issue by marius240** [mobizt/Firebase-ESP32#10]
I get this error when i just try to compile the library

fatal error: HTTPClientESP32Ex.h: No such file or directory

Help anyone?

**Comment by mobizt** [comment]
You need to install [HTTPClientESP32Ex library ](https://github.com/mobizt/HTTPClientESP32Ex)

**Comment by marius240** [comment]
oh ok cool

**Comment by marius240** [comment]
quick qustion,

why doesnt this work?

 Firebase.setString("lul","lul");

**Comment by marius240** [comment]
this doesnt work either:

Firebase.setInt("lul",2);

**Comment by mobizt** [comment]
See how to use in examples because API is different. Post your code for better hep.

**Comment by mobizt** [comment]
You need to modify your original code to match my API calls.

**Comment by marius240** [comment]
hm ok cheking it out now
