### ISSUE TITLE
ENHANCEMENT Cloud Firestore

### ISSUE THREAD

**Issue by jshep321** [mobizt/Firebase-ESP32#101]
**Is your feature request related to a problem? Please describe.**
Has anyone worked on similar library for the Cloud Firestore?  

I've found some other examples using intermediaries (cloud functions, etc.), but nothing direct.

**Comment by mobizt** [comment]
I didn't see your issue related to the library.

FYI: https://github.com/mobizt/Firebase-ESP32/issues/83#issuecomment-655967128
