### ISSUE TITLE
Unable to understand how to use the library

### ISSUE THREAD

**Issue by Parthavu** [mobizt/Firebase-ESP32#102]
There are absolutely no resources to the usage of this library that I could find other than the README file from which I couldn't understand how to get anything done. The example sketches didn't exactly help either.  Could you please refer me to a good easy to understand source of information on how to use this library. Thank you in advance.

**Comment by mobizt** [comment]
I think you are new to Arduino and don't even know that many good written libraries provide the examples belong to the libraries you downloaded and installed which you can open it in Arduino IDE.

From Arduino IDE choose menu **File** > **Examples** > **Firebase ESP32 Client**  and choose one from 27 available examples.

You can start from the **Beginner_start_here.ino** then the **Basic.ino** example

Also on the Github repo, you can check the examples folder [here](https://github.com/mobizt/Firebase-ESP32/tree/master/examples) and for the [function and method references here](https://github.com/mobizt/Firebase-ESP32/tree/master/src).
