### ISSUE TITLE
Help needed, Hi mobizt!

### ISSUE THREAD

**Issue by mazorvanunu** [mobizt/Firebase-ESP32#104]
Am not sure if this is the place to ask\put it but after search for the subject and finding no answers i thought i'de try here, apologies if I have been missing something basic.
i am using firebase to send data to a realtime server and it works great, the problem begins when i try to do it (on the same platform) using cellular data (LTE) with the esp32 w-rover-b board, the network connects and i can send http requests..
Is this possible? again sorry if im missing something basic however i could not find any reference regarding the issue
If this is a known issue, is there anyway around it? other than connecting to a wifi that is.. 
Thanks in advance!

**Comment by mobizt** [comment]
Not support any GSM module or AT firmware or any network to serial bridge, ESP32 only.
