### ISSUE TITLE
Stream cannot recover after internet restore

### ISSUE THREAD

**Issue by chauzov1995** [mobizt/Firebase-ESP32#108]
We simulate the situation: esp32 is connected to wi-fi, wi-fi has Internet access. We turn off the Internet on the router, then turn the Internet back on in a minute. The stream could not recover. There will be all the time - Stream timeout, resume streaming ...
Add a function to check if the stream is alive.

**Comment by mobizt** [comment]
This is done internally and heavily discussion on this many times.

**Comment by mobizt** [comment]
This is your internet connection issue.

Nothing to add for that but you can check the bool returns from **httpConnected()** method of Firebase Data object that you use for stream.

The **httpConnected()** will be true when stream connection is alive as the stream is connected (not the WiFi or internet status).

**Comment by mobizt** [comment]
You can use **streamTimeout()** method of Firebase Data object that used for stream to check the stream connection too. 

That's the method use in the stream examples (not a stream callback), please check.
