### ISSUE TITLE
Incorrect Board chosen

### ISSUE THREAD

**Issue by rubenrutjens** [mobizt/Firebase-ESP32#116]
**Describe the bug**
Installed the ESP32 Library (Latest 3.8.9). Got some example code, but whenever I try to run the program it gives me the following error:
`Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.h:43:10: fatal error: memory: No such file or directory
 #include <memory>
          ^~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Uno.
`

**Expected behavior**
Working library for me to be able to connect my esp32 to firebase

**Screenshots**
https://imgur.com/oRZwuux

**IDE and its version:**
 - Arduino
 - Latest

**Comment by mobizt** [comment]
This library for ESP32. You currently choose the Arduino Uno board.
