### ISSUE TITLE
BUG ESP32 Using BLE and Firebase same time causes memory error.

### ISSUE THREAD

**Issue by 0100101101001011** [mobizt/Firebase-ESP32#117]
**Describe the bug**
When I try to use Arduino BLE and this library at the same time. The esp32 crashes.

**To Reproduce**

**Expected behavior**

**Screenshots**

**IDE and its version:**
 - Arduino, PlatformIO
 - Version [e.g. 1.8.9]

**ESP8266 Arduino Core SDK version**
 - Version [e.g. 2.5.1]

**Additional context**

**Comment by mobizt** [comment]
Please search google How to use Bluetooth and WiFi at the same time?
It's currently not possible unless Espressif update the firmware.

**Comment by mobizt** [comment]
If the Bluetooth and WiFi coexistent is possible, see the FAQ 5.3.2
https://www.espressif.com/sites/default/files/documentation/ESP32_FAQs__EN.pdf

It needs to config in menuconfig under ESP-IDF.

**Comment by mobizt** [comment]
While Bluetooth is enable, please try the example in Arduino IDE examples about HTTPS request.
If you get the exception error, you can't use both WiFi and Bluetooth simultaneously as you don't have enough memory.
