### ISSUE TITLE
ESP32S2 warnings

### ISSUE THREAD

**Issue by poli44** [mobizt/Firebase-ESP32#118]
Hi, When compiling for ESP32S2 i got this. There is a chance to remove these warnings.

`In file included from /Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:40:
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:589:10: error: 'vector' in namespace 'std' does not name a template type
     std::vector<std::string> _pathTk = std::vector<std::string>();
          ^~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:589:5: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:46:1:
+#include <vector>
 
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:589:5:
     std::vector<std::string> _pathTk = std::vector<std::string>();
     ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:590:10: error: 'vector' in namespace 'std' does not name a template type
     std::vector<eltk_t> _eltk = std::vector<eltk_t>();
          ^~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:590:5: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
     std::vector<eltk_t> _eltk = std::vector<eltk_t>();
     ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:591:10: error: 'vector' in namespace 'std' does not name a template type
     std::vector<el_t> _el = std::vector<el_t>();
          ^~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:591:5: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
     std::vector<el_t> _el = std::vector<el_t>();
     ^~~
In file included from /Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:40:
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:646:48: error: 'std::vector' has not been declared
     void _strToTk(const std::string &str, std::vector<std::string> &cont, char delim);
                                                ^~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.h:646:54: error: expected ',' or '...' before '<' token
     void _strToTk(const std::string &str, std::vector<std::string> &cont, char delim);
                                                      ^
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'bool FirebaseJson::get(FirebaseJsonData&, const String&, bool)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:388:28: error: '_pathTk' was not declared in this scope
     _strToTk(path.c_str(), _pathTk, '/');
                            ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:388:28: note: suggested alternative: '_lastTk'
     _strToTk(path.c_str(), _pathTk, '/');
                            ^~~~~~~
                            _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'size_t FirebaseJson::iteratorBegin(const char*)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:427:5: error: '_eltk' was not declared in this scope
     _eltk.clear();
     ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:430:5: error: '_el' was not declared in this scope
     _el.clear();
     ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:430:5: note: suggested alternative: '_nl'
     _el.clear();
     ^~~
     _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::iteratorEnd()':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:438:5: error: '_eltk' was not declared in this scope
     _eltk.clear();
     ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::iteratorGet(size_t, int&, String&, String&)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:450:9: error: '_eltk' was not declared in this scope
     if (_eltk.size() < index + 1)
         ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:458:9: error: '_eltk' was not declared in this scope
     if (_eltk[index].type == 0)
         ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_jsmn_parse(bool)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:503:5: error: '_eltk' was not declared in this scope
     _eltk.clear();
     ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_setMark(int, bool)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:538:28: error: '_el' was not declared in this scope
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:538:28: note: suggested alternative: '_nl'
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
                            _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_setSkip(int, bool)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:550:28: error: '_el' was not declared in this scope
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:550:28: note: suggested alternative: '_nl'
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
                            _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_setRef(int, bool)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:562:28: error: '_el' was not declared in this scope
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:562:28: note: suggested alternative: '_nl'
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
                            _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_getTkIndex(int, tk_index_t&)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:587:28: error: '_el' was not declared in this scope
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:587:28: note: suggested alternative: '_nl'
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
                            _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'bool FirebaseJson::_updateTkIndex(uint16_t, int&, char*, int, char*, PRINT_MODE, bool)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:609:28: error: '_el' was not declared in this scope
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:609:28: note: suggested alternative: '_nl'
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
                            _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:667:65: error: '_pathTk' was not declared in this scope
                                     if (_parseCompleted == (int)_pathTk.size())
                                                                 ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:667:65: note: suggested alternative: '_lastTk'
                                     if (_parseCompleted == (int)_pathTk.size())
                                                                 ^~~~~~~
                                                                 _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:691:73: error: '_pathTk' was not declared in this scope
                                             if (_parseCompleted == (int)_pathTk.size())
                                                                         ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:691:73: note: suggested alternative: '_lastTk'
                                             if (_parseCompleted == (int)_pathTk.size())
                                                                         ^~~~~~~
                                                                         _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:707:51: error: '_pathTk' was not declared in this scope
                                 _parseCompleted = _pathTk.size();
                                                   ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:707:51: note: suggested alternative: '_lastTk'
                                 _parseCompleted = _pathTk.size();
                                                   ^~~~~~~
                                                   _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'bool FirebaseJson::_updateTkIndex2(std::__cxx11::string&, uint16_t, int&, char*, int, char*, PRINT_MODE)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:740:28: error: '_el' was not declared in this scope
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:740:28: note: suggested alternative: '_nl'
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
                            _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'bool FirebaseJson::_updateTkIndex3(uint16_t, int&, char*, int, PRINT_MODE)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:804:28: error: '_el' was not declared in this scope
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:804:28: note: suggested alternative: '_nl'
     for (size_t i = 0; i < _el.size(); i++)
                            ^~~
                            _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_insertChilds(char*, PRINT_MODE)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:869:18: error: '_pathTk' was not declared in this scope
     for (int i = _pathTk.size() - 1; i > _parseCompleted - 1; i--)
                  ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:869:18: note: suggested alternative: '_lastTk'
     for (int i = _pathTk.size() - 1; i > _parseCompleted - 1; i--)
                  ^~~~~~~
                  _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:886:14: error: '_pathTk' was not declared in this scope
     if ((int)_pathTk.size() == _parseCompleted)
              ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:886:14: note: suggested alternative: '_lastTk'
     if ((int)_pathTk.size() == _parseCompleted)
              ^~~~~~~
              _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_addArrNodes(std::__cxx11::string&, std::__cxx11::string&, int, char*, PRINT_MODE)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:908:31: error: '_pathTk' was not declared in this scope
             if (index == (int)_pathTk.size() - 1)
                               ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:908:31: note: suggested alternative: '_lastTk'
             if (index == (int)_pathTk.size() - 1)
                               ^~~~~~~
                               _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_addObjNodes(std::__cxx11::string&, std::__cxx11::string&, int, char*, PRINT_MODE)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:941:12: error: '_pathTk' was not declared in this scope
     str += _pathTk[index].c_str();
            ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:941:12: note: suggested alternative: '_lastTk'
     str += _pathTk[index].c_str();
            ^~~~~~~
            _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_parseToken(uint16_t&, char*, int&, char*, int, PRINT_MODE)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:984:26: error: '_pathTk' was not declared in this scope
                 if ((int)_pathTk.size() != _parseDepth + 1)
                          ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:984:26: note: suggested alternative: '_lastTk'
                 if ((int)_pathTk.size() != _parseDepth + 1)
                          ^~~~~~~
                          _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1045:26: error: '_pathTk' was not declared in this scope
                 if ((int)_pathTk.size() != _parseDepth + 1)
                          ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1045:26: note: suggested alternative: '_lastTk'
                 if ((int)_pathTk.size() != _parseDepth + 1)
                          ^~~~~~~
                          _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1140:9: error: '_el' was not declared in this scope
         _el.push_back(e);
         ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1140:9: note: suggested alternative: '_nl'
         _el.push_back(e);
         ^~~
         _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1183:17: error: '_eltk' was not declared in this scope
                 _eltk.push_back(el);
                 ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1245:17: error: '_eltk' was not declared in this scope
                 _eltk.push_back(el);
                 ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_compileToken(uint16_t&, char*, int&, char*, int, PRINT_MODE, char*, int, bool)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1279:26: error: '_pathTk' was not declared in this scope
                 if ((int)_pathTk.size() != _parseDepth + 1)
                          ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1279:26: note: suggested alternative: '_lastTk'
                 if ((int)_pathTk.size() != _parseDepth + 1)
                          ^~~~~~~
                          _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1331:26: error: '_pathTk' was not declared in this scope
                 if ((int)_pathTk.size() != _parseDepth + 1)
                          ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1331:26: note: suggested alternative: '_lastTk'
                 if ((int)_pathTk.size() != _parseDepth + 1)
                          ^~~~~~~
                          _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1377:35: error: '_pathTk' was not declared in this scope
                 _parseCompleted = _pathTk.size();
                                   ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1377:35: note: suggested alternative: '_lastTk'
                 _parseCompleted = _pathTk.size();
                                   ^~~~~~~
                                   _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1427:9: error: '_el' was not declared in this scope
         _el.push_back(e);
         ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1427:9: note: suggested alternative: '_nl'
         _el.push_back(e);
         ^~~
         _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_removeToken(uint16_t&, char*, int&, char*, int, PRINT_MODE, char*, int, bool)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1627:9: error: '_el' was not declared in this scope
         _el.push_back(e);
         ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1627:9: note: suggested alternative: '_nl'
         _el.push_back(e);
         ^~~
         _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'single_child_parent_t FirebaseJson::_findSCParent(int)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1756:32: error: '_el' was not declared in this scope
         for (size_t j = 0; j < _el.size(); j++)
                                ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1756:32: note: suggested alternative: '_nl'
         for (size_t j = 0; j < _el.size(); j++)
                                ^~~
                                _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: At global scope:
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1809:58: error: 'std::vector' has not been declared
 void FirebaseJson::_strToTk(const std::string &str, std::vector<std::string> &cont, char delim)
                                                          ^~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1809:64: error: expected ',' or '...' before '<' token
 void FirebaseJson::_strToTk(const std::string &str, std::vector<std::string> &cont, char delim)
                                                                ^
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_strToTk(const string&, int)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1812:24: error: 'delim' was not declared in this scope
     current = str.find(delim);
                        ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1812:24: note: suggested alternative: 'delay'
     current = str.find(delim);
                        ^~~~~
                        delay
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1819:13: error: 'cont' was not declared in this scope
             cont.push_back(s);
             ^~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1819:13: note: suggested alternative: '_int'
             cont.push_back(s);
             ^~~~
             _int
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1827:9: error: 'cont' was not declared in this scope
         cont.push_back(s);
         ^~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1827:9: note: suggested alternative: '_int'
         cont.push_back(s);
         ^~~~
         _int
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_parse(const char*, PRINT_MODE)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1850:20: error: '_pathTk' was not declared in this scope
     _strToTk(path, _pathTk, '/');
                    ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1850:20: note: suggested alternative: '_lastTk'
     _strToTk(path, _pathTk, '/');
                    ^~~~~~~
                    _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1869:5: error: '_el' was not declared in this scope
     _el.clear();
     ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1869:5: note: suggested alternative: '_nl'
     _el.clear();
     ^~~
     _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1870:5: error: '_eltk' was not declared in this scope
     _eltk.clear();
     ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::clearPathTk()':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1900:18: error: '_pathTk' was not declared in this scope
     size_t len = _pathTk.size();
                  ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1900:18: note: suggested alternative: '_lastTk'
     size_t len = _pathTk.size();
                  ^~~~~~~
                  _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1906:10: error: 'vector' is not a member of 'std'
     std::vector<std::string>().swap(_pathTk);
          ^~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1906:10: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:41:1:
+#include <vector>
 
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1906:10:
     std::vector<std::string>().swap(_pathTk);
          ^~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1906:28: error: expected primary-expression before '>' token
     std::vector<std::string>().swap(_pathTk);
                            ^
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1906:30: error: expected primary-expression before ')' token
     std::vector<std::string>().swap(_pathTk);
                              ^
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'bool FirebaseJson::_isArrTk(int)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1994:22: error: '_pathTk' was not declared in this scope
     if (index < (int)_pathTk.size())
                      ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:1994:22: note: suggested alternative: '_lastTk'
     if (index < (int)_pathTk.size())
                      ^~~~~~~
                      _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'bool FirebaseJson::_isStrTk(int)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2001:22: error: '_pathTk' was not declared in this scope
     if (index < (int)_pathTk.size())
                      ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2001:22: note: suggested alternative: '_lastTk'
     if (index < (int)_pathTk.size())
                      ^~~~~~~
                      _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'int FirebaseJson::_getArrIndex(int)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2010:22: error: '_pathTk' was not declared in this scope
     if (index < (int)_pathTk.size())
                      ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2010:22: note: suggested alternative: '_lastTk'
     if (index < (int)_pathTk.size())
                      ^~~~~~~
                      _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJson::_set(const char*, const char*)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2161:20: error: '_pathTk' was not declared in this scope
     _strToTk(path, _pathTk, '/');
                    ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2161:20: note: suggested alternative: '_lastTk'
     _strToTk(path, _pathTk, '/');
                    ^~~~~~~
                    _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2181:5: error: '_el' was not declared in this scope
     _el.clear();
     ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2181:5: note: suggested alternative: '_nl'
     _el.clear();
     ^~~
     _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2182:5: error: '_eltk' was not declared in this scope
     _eltk.clear();
     ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'bool FirebaseJson::remove(const String&)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2239:28: error: '_pathTk' was not declared in this scope
     _strToTk(path.c_str(), _pathTk, '/');
                            ^~~~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2239:28: note: suggested alternative: '_lastTk'
     _strToTk(path.c_str(), _pathTk, '/');
                            ^~~~~~~
                            _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2258:5: error: '_el' was not declared in this scope
     _el.clear();
     ^~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2258:5: note: suggested alternative: '_nl'
     _el.clear();
     ^~~
     _nl
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2259:5: error: '_eltk' was not declared in this scope
     _eltk.clear();
     ^~~~~
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'bool FirebaseJsonArray::_get(FirebaseJsonData&, const char*)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2694:41: error: 'class FirebaseJson' has no member named '_pathTk'; did you mean '_lastTk'?
     _json._strToTk(path2.c_str(), _json._pathTk, '/');
                                         ^~~~~~~
                                         _lastTk
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp: In member function 'void FirebaseJsonArray::_set(const char*, const char*, bool)':
/Users/mariuszperkowski/Documents/Arduino/libraries/Firebase-ESP32-master/src/FirebaseJson.cpp:2785:33: error: 'class FirebaseJson' has no member named '_pathTk'; did you mean '_lastTk'?
     _json._strToTk(path2, _json._pathTk, '/');
                                 ^~~~~~~
                                 _lastTk`

**Comment by mobizt** [comment]
Are you sure you set up all the IDE and Arduino ESP32 core SDK correctly?

This is the compiler error due to missing some tool chains.

**Comment by poli44** [comment]
xtensa-esp32s2-elf-g++

**Comment by mobizt** [comment]
The error due to the vector and it's already included [here](https://github.com/mobizt/Firebase-ESP32/blob/master/src/FirebaseJson.h#L44).

The lines at the error showed are different from the latest source of library. Do you use the outdated version or corrupted files?

Please update the library.

**Comment by poli44** [comment]
I added  #include <vector> to file FirebaseJson.h and it help. Thanks.

**Comment by poli44** [comment]
![Zrzut ekranu 2020-12-2 o 09 39 08](https://user-images.githubusercontent.com/31142293/100849216-88c5f680-3482-11eb-910c-bb9de3ad2abe.png)

**Comment by mobizt** [comment]
It different and my cause the conflicts and unexpected error due to you may ever installed the FirebaseJson library which may outdated and is not completely compatible with the one use in the Firebase library.

You should install the latest Firebase version.
