### ISSUE TITLE
HELP - Root CACert renewal

### ISSUE THREAD

**Issue by miqaP** [mobizt/Firebase-ESP32#119]
Hi,
I'm trying to understand the process that secure the connection between the device and Firebase. 
I understand that the Firebase CACert will at some time expires, when it will happen the communication between Firebase and the device will be broken.

I suppose I need to upgrade the device firmware each time the cert expires. The problem is that my device upgrade process is handled by firebase (the firmware is stored on Firebase). So if the certificate expires I will not be able to connect to firebase to get the new certificate.

How I am supposed to handle the CACert renewal in this case ?
Is my upgrade process broken by design ? Is there a better way to do this ?

Kind regards,

**Comment by mobizt** [comment]
You can provide the certificate to user device via local access (sd card, serial, mesh, bluetooth) and remote access .

You can set up your own server and do the port forwarding or setup some dns or pay for some cloud server service.

However you still need the server to backup and provide any services to your user.
