### ISSUE TITLE
Error on FirebaseESP32.cpp str.erase(std::remove

### ISSUE THREAD

**Issue by GuilhermeKROSS** [mobizt/Firebase-ESP32#12]
Hi, i'm having the following error message when i compile my project:

...\Arduino\libraries\Firebase-ESP32-master\src\FirebaseESP32.cpp: In member function 'std::__cxx11::string FirebaseESP32::trim(std::__cxx11::string&)':

...\Arduino\libraries\Firebase-ESP32-master\src\FirebaseESP32.cpp:2030:13: error: 'remove' is not a member of 'std'

str.erase(std::remove(str.begin(), str.end(), '\r'), str.end());

I have commented the lines  2030 and 2031. Doing this i can compile and download. Everything seems to be ok with that.
mobizt Thaks for this amazing work you did and for sharing this great lib with us

**Comment by mobizt** [comment]
You're welcome and thank you for let me know.
I will fix this in the next update.

**Comment by mobizt** [comment]
I just update to version 2.3.3. Do you still get error when set data?

**Comment by GuilhermeKROSS** [comment]
> I just update to version 2.3.3. Do you still get error when set data?

Now everything works fine. Thanks again. Have a good day!
