### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by TechTSDHacking** [mobizt/Firebase-ESP32#127]
**Describe the bug**
Its not working on esp32 ttgo tcall

**To Reproduce**

**Expected behavior**

**Screenshots**

**IDE and its version:**
 - Arduino, PlatformIO
 - Version [e.g. 1.8.9]

**ESP8266 Arduino Core SDK version**
 - Version [e.g. 2.5.1]

**Additional context**

**Comment by mobizt** [comment]
Are you know how to use GitHub?

If not, see how other people do.
