### ISSUE TITLE
TTGO T CALL module not connect to firebase.....please help...

### ISSUE THREAD

**Issue by SANKETSUPEKAR** [mobizt/Firebase-ESP32#130]
// TTGO T-Call pin definitions
#define MODEM_RST            5
#define MODEM_PWKEY          4
#define MODEM_POWER_ON       23
#define MODEM_TX             27
#define MODEM_RX             26
#define I2C_SDA              21
#define I2C_SCL              22

#include "FirebaseESP32.h"
#define FIREBASE_HOST "esp32-7af23-default-rtdb.firebaseio.com"
#define FIREBASE_AUTH "S9Frjhe8ACepN37sbezZoOZJbQDDmazR63QjJpmT"

FirebaseData firebaseData;

String nodo="/Sensors";
bool iterar=true;

#include <TinyGPS++.h> //https://github.com/mikalhart/TinyGPSPlus
#include <AceButton.h> // https://github.com/bxparks/AceButton
#define TINY_GSM_MODEM_SIM800
#include <TinyGsmClient.h> // https://github.com/vshymanskyy/TinyGSM
#include <Wire.h>
#include "utilities.h"

// Emergency Number and Message
String message = "It's an Emergency. I'm at this location ";
String mobile_number = "9130420859";
String message_with_data;

// Set serial for GPS Module
#define SerialMon Serial
// Hardware Serial for builtin GSM Module
#define SerialAT Serial1

const char apn[]  = "airtelgprs.com";
const char user[] = "";
const char pass[] = "";

//static const int RXPin = 4, TXPin = 5;
static const uint32_t GPSBaud = 9600;

TinyGsm modem(SerialAT);

unsigned int move_index = 1;

void setup()
{
  // Set console baud rate
  Serial.begin(9600);
  delay(10);

  // Keep power when running from battery
  Wire.begin(I2C_SDA, I2C_SCL);
  bool   isOk = setPowerBoostKeepOn(1);
  SerialMon.println(String("IP5306 KeepOn ") + (isOk ? "OK" : "FAIL"));

  // Set-up modem reset, enable, power pins
  pinMode(MODEM_PWKEY, OUTPUT);
  pinMode(MODEM_RST, OUTPUT);
  pinMode(MODEM_POWER_ON, OUTPUT);

  digitalWrite(MODEM_PWKEY, LOW);
  digitalWrite(MODEM_RST, HIGH);
  digitalWrite(MODEM_POWER_ON, HIGH);

  // Set GSM module baud rate and UART pins
  SerialAT.begin(115200, SERIAL_8N1, MODEM_RX, MODEM_TX);
  delay(3000);

  // Restart takes quite some time
  // To skip it, call init() instead of restart()
  SerialMon.println("Initializing modem...");
  modem.restart();

  String modemInfo = modem.getModemInfo();
  SerialMon.print("Modem: ");
  SerialMon.println(modemInfo);

  // Unlock your SIM card with a PIN
  //modem.simUnlock("1234");

  SerialMon.print("Waiting for network...");
  if (!modem.waitForNetwork(240000L)) {
    SerialMon.println(" fail");
    delay(10000);
    return;
  }
  SerialMon.println(" OK");

  if (modem.isNetworkConnected()) {
    SerialMon.println("Network connected");
  }

  SerialMon.print(F("Connecting to APN: "));
  SerialMon.print(apn);
  if (!modem.gprsConnect(apn, user, pass)) {
    SerialMon.println(" fail");
    delay(10000);
    return;
  }
  SerialMon.println(" OK");
   Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
   
  //  ss.begin(GPSBaud);
}

void loop()
{

  while(iterar)
  {
    Firebase.getInt(firebaseData,nodo + "/sensor1");
    Serial.println(firebaseData.intData());
    delay(250);
    Firebase.getString(firebaseData,nodo + "/sensor2");
    Serial.println(firebaseData.stringData());
    iterar=false;
    Firebase.end(firebaseData);
  }
   /*if(modem.sendSMS(mobile_number, message)){
    SerialMon.println(message);
  }
  else{
    SerialMon.println("SMS failed to send");
  }*/
delay(1000);
}

**Comment by mobizt** [comment]
The library is only for WiFi and Ethernet connection.
Any modem, AT command, UART serial bridge (onboard or external) is not supported.
