### ISSUE TITLE
HELP(I think)

### ISSUE THREAD

**Issue by Grabt234** [mobizt/Firebase-ESP32#132]
Hi, still new to Github and Firebase so apologies if I am simply missing something.

I have been working in a small project and have included the latest version of you ESP mail client library and Firebase library and I am getting compilation errors. It looks like there are redefinitions of HTTP and SSL structures that are causing this issue. Should I try rename these structures and if so is there a standard naming convention that is good practice to use?

G.

**Comment by mobizt** [comment]
The FirebaseESP32 and ESP Mail Client are now updated to prevent naming conflicts.
Please update.
