### ISSUE TITLE
streamTimeoutCallback doesn't trigger when there is SSL error.

### ISSUE THREAD

**Issue by 0100101101001011** [mobizt/Firebase-ESP32#136]
**Describe the problem**
I am testing the stream callback code. I noticed if there is a problem with the SSL connection, the streamTimeoutCallback does not get called. Following is the serial output during the SSL connection error.

**To Reproduce**
```
[E][fb_ssl_client32.cpp:98] start_ssl_client(): Connect to Server failed!
[E][FB_WCS32.cpp:160] connect(): start_ssl_client: -1
```

**Comment by mobizt** [comment]
The stream timeout still working correctly but the timeout callback will be notified at some interval time since the stream connection failed to prevent too much notify status printed on the serial.

**Comment by mobizt** [comment]
This is the library design.

**Comment by mobizt** [comment]
Don't use the stream timeout callback to perform your work. 
It design for notification at some interval only.

You should use fbdo.httpConnected(); which returns true when the server connection established and should return true as long as the stream connection is keep alive and return false when the stream timed out or connection disconnected.

**Comment by 0100101101001011** [comment]
Thank you for helping! This library is amazing:)
