### ISSUE TITLE
RELIABILITY

### ISSUE THREAD

**Issue by Murtaza7745** [mobizt/Firebase-ESP32#140]
Which of your library is more reliable for Firebase Realtime Database for esp32 from production view point,
[https://github.com/mobizt/Firebase-ESP32](url)  or  [https://github.com/mobizt/Firebase-ESP-Client](url)?

**Comment by mobizt** [comment]
For RTDB, the internal processes for both libraries are the same. 
The only different is the functions interfaces.

**Comment by Murtaza7745** [comment]
ok thanks
