### ISSUE TITLE
Ethernet Usage

### ISSUE THREAD

**Issue by simeon9696** [mobizt/Firebase-ESP32#144]
Hi, can this library be used with ethernet?

**Comment by mobizt** [comment]
It's not yet tested with Ethernet.
You can try with your hardware.

**Comment by mobizt** [comment]
Now Ethernet is supported. Please update the library.

This is the [Ethernet usage example](https://github.com/mobizt/Firebase-ESP32/tree/master/examples/Basic_with_Ethernet).
