### ISSUE TITLE
ENHANCEMENT

### ISSUE THREAD

**Issue by petkomatus** [mobizt/Firebase-ESP32#146]
Can you help me send a message to Firebase.setString (fbdo, "message", "/"Arduino\nESP32/"");

i don't know about the top ride

Well thank you

**Comment by mobizt** [comment]
I don't see any problem.
If you want to construct string from hard code the character inside quotes e.g. "your string" and your string contains quote " you should make a escape string by place \ before " e.g.

String str = "abcde \\"fghi\\" jklmn"; 

It will interpret as abcde "fghi" jklmn.

**Comment by petkomatus** [comment]
i need to send to firebase in this shape
![Screenshot 2021-02-19 13 41 50](https://user-images.githubusercontent.com/5622850/108506155-a7d16900-72b8-11eb-97f4-5377805df768.png)

**Comment by mobizt** [comment]
You should search Google for escape sequence string.

Test it by print to serial before sending.

String s1 = "\\"Arduino\nESP32\\"";

Serial.println(s1) 

This will pint  
**\"Arduino
ESP32\"**

 String s2 = "\\\\\\"Arduino\\nESP32\\\\\\""; 

This will pint  
**\\"Arduino\\nESP32\\\"**

**Comment by petkomatus** [comment]
well thank you
