### ISSUE TITLE
HELP, im having a issue sending large values trought Firebase Database

### ISSUE THREAD

**Issue by Niassamond** [mobizt/Firebase-ESP32#156]
Hello, im having a small issue when using the command:
 if (Firebase.setString(fbdo2, path , data))
Im trying to send in huge strings that have from 4k to 11k letters.
it works fine the first 2 times, but after that it gets a weird bug, and resets the ESP32.
I always get this same error:
bort() was called at PC 0x4017d0d3 on core 1
Backtrace: 0x4009140c:0x3ffb19a0 0x4009163d:0x3ffb19c0 0x4017d0d3:0x3ffb19e0 0x4017d11a:0x3ffb1a00 0x4017c02f:0x3ffb1a20 0x4017c13a:0x3ffb1a40 0x4017c0d9:0x3ffb1a60 0x400d98fd:0x3ffb1a80 0x400ddd07:0x3ffb1aa0 0x400de928:0x3ffb1d70 0x400dee91:0x3ffb1d90 0x400def47:0x3ffb1dc0 0x400df0ca:0x3ffb1e70 0x400df135:0x3ffb1f30 0x400d4eff:0x3ffb1f50 0x400d2d56:0x3ffb1f70 0x400eac01:0x3ffb1fb0 0x4008db55:0x3ffb1fd0
I checked the backtracer and it comes back to the line i first posted.
Can someone please help me fix this issue?
Also im currently using the Firebase ESP32 Client Version 3.8.22

**Comment by mobizt** [comment]
Memory is not sufficient in your device cause memory allocation failed.

It' not possible to  do that in embedded device ram. 

You can store large file in flash or sd by using [this](https://github.com/mobizt/Firebase-ESP32/tree/master/src#set-binary-data-from-the-file-store-on-sd-cardflash-memory-to-the-defined-database-path).
