### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Karandalwani** [mobizt/Firebase-ESP32#169]
How to read string data from firebase

**Comment by mobizt** [comment]
https://github.com/mobizt/Firebase-ESP32/tree/master/src#read-the-string-of-text-at-the-defined-database-path-1

And to get string from Firebase Data object
https://github.com/mobizt/Firebase-ESP32/blob/master/src/addons/RTDBHelper.h#L16

**Comment by Karandalwani** [comment]
Thank you 😀
