### ISSUE TITLE
FirebaseDatbaseObject.jsonObject(), BUG

### ISSUE THREAD

**Issue by Amey112** [mobizt/Firebase-ESP32#171]
fbdo.jsonObject() possibly returning an empty JSON object. 
Whenever I try to use fbdo.jsonObject() in my code, the code runs but the jsonObject returned is empty. I check it using toString() function and the printed output is : {}
But whenever I use jsonString() function on the database object and print the string, the string has information from the firestore.  

**To Reproduce**
1. setup a firebase connection and get the parent node using Firebase.getJSON(fbdo, parentPath);
2. FirebaseJson &json = fbdo.jsonObject();
3. String jsonString
4. json.toString(jsonString, true);
5. Serial.println(jsonString);                            //This is printed as empty {} . 
6. Serial.println(fbdo.jsonString());                 //Here all the information is printed. 

**Expected behavior**
the fbdo.jsonObject() should return a valid JsonObject.

**Screenshots**
![image](https://user-images.githubusercontent.com/67439149/123525448-5154bb00-d6ee-11eb-91e6-e28906676f17.png)

**IDE and its version:**
 - Arduino - Version 
**ESP8266 Arduino Core SDK version**
 - Version 1.8.15

**Comment by mobizt** [comment]
Thanks for report this.

The library updated and issue was fixed in [v3.10.3](https://github.com/mobizt/Firebase-ESP32/releases/tag/v3.10.3).

Please update.
