### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Amey112** [mobizt/Firebase-ESP32#172]
![image](https://user-images.githubusercontent.com/67439149/123655328-7fe8a800-d84c-11eb-895d-d33ee23bdec3.png)

The esp32 weirdly bugs out unexpectedly.

![image](https://user-images.githubusercontent.com/67439149/123655543-b1617380-d84c-11eb-8485-a52b4645e5a0.png)

**Comment by mobizt** [comment]
You need to post the clean, clear and minimal code here for everyone can reproduce the error.

**Comment by mobizt** [comment]
Decode stack can't help without your code and it's related to your code rather than the library issue.
