### ISSUE TITLE
Can't send json to Firebase (please help)

### ISSUE THREAD

**Issue by juliusfelix12** [mobizt/Firebase-ESP32#187]
Hi sir, why i can't send JSON string to firebase, which part i do wrong?? I used to read the documentation and still not find the solution, please help thankyou.
![image](https://user-images.githubusercontent.com/71480360/131304249-cb5e84e2-42fd-4880-98a5-c87c5b211f16.png)

I expect the output on firebase will be like this
![image](https://user-images.githubusercontent.com/71480360/131304441-e719580b-3f91-4692-bdf5-ee5199d84eb0.png)

**Comment by mobizt** [comment]
You should read the document.
https://github.com/mobizt/Firebase-ESP32/tree/master/src#set-child-nodes-key-and-value-using-firebasejson-object-to-the-defined-database-path

You can't set the serialized JSON string to that function which accept only FirebaseJson object.

The library has built-in JSON builder and parser, [FirebaseJson](https://github.com/mobizt/Firebase-ESP32/tree/master/src#firebasejson-object-functions) to serialize and deserialize JSON which is easier and efficient.

**Comment by mobizt** [comment]
The examples related to FirebaseJson are [here](https://github.com/mobizt/Firebase-ESP32/tree/master/examples/FirebaseJson/examples).

**Comment by mobizt** [comment]
You should update the library to latest version to use the new core of FirebaseJson which is powered by the best JSON parser, [cJSON](https://github.com/DaveGamble/cJSON).

**Comment by mobizt** [comment]
This is the [example](https://github.com/mobizt/Firebase-ESP32/blob/master/examples/FirebaseJson/examples/Client/Firebase/Firebase.ino) when using FirebaseJson and Firebase RTDB.

**Comment by juliusfelix12** [comment]
thankyou sir for helping!

**Comment by juliusfelix12** [comment]
sir @mobizt , i already read and apply code from the documentation like this and it works!
![image](https://user-images.githubusercontent.com/71480360/131315505-e1339a86-5bc7-4f0e-80eb-72e93914ebea.png)

but why it doesn't generate random key like this as a child for every read data??
![image](https://user-images.githubusercontent.com/71480360/131315710-9ffbecc5-bc77-4e13-99c6-5b0d85eab607.png)

pls help thanks

**Comment by mobizt** [comment]
You can use pushJSON to push the new random key name to that node.

**Comment by juliusfelix12** [comment]
thanks a lot sir!!!
