### ISSUE TITLE
MultiPathStream and DHT22

### ISSUE THREAD

**Issue by fubl84** [mobizt/Firebase-ESP32#192]
Thank you for this whole library! It makes communication with the firebase really easy. 
I'm using your library to sync data between a firebase realtime database and an esp32. 
And for some reason the .setMutliPathStreamCallback function conflicts with the DHT22 (DHT sensor library@^1.4.2 & Adafruit Unified Sensor@^1.1.4).
With the StreamCallback in setup I'm getting nan-values from the DHT and if I comment the function out the readings are just fine. 
To further test this, I set the first dht reading just before the .setMultiPathStreamCallback and it put out normal values - and after the callback-function I get the nan-messages from the dht.

Do you have any idea, why that might be the case? Is there something conflicting with the libraries or is it just stupidity on my part?

Here's the code:

```cpp
String parentPath = "/greenhouse";
String childPath[19] = {"/heatmat", "/humidifier", "/offsetHumidity", "/lights", "/minHumidity", "/remote", "/standby", "/ventilator", "/timerRemote/startH", "/timerRemote/startM", "/timerRemote/stopH", "/timerRemote/stopM", "/timerLights/startH", "/timerLights/startM", "/timerLights/stopH", "/timerLights/stopM", "/daylightOffset", "/remoteMan", "/lightsMan"};
size_t childPathSize = 19;

FirebaseData database;
FirebaseData stream;

FirebaseAuth auth;
FirebaseConfig config;

Relay ventilator(RELAY_VENTILATOR, false, "/greenhouse/ventilator");
Relay humidifier(RELAY_HUMIDIFIER, false, "/greenhouse/humidifier");
Relay heatmat(RELAY_HEATMAT, false, "/greenhouse/heatmat");
Relay remote(RELAY_REMOTE, false, "/greenhouse/remote");
Relay lights(RELAY_LIGHTS, false, "/greenhouse/lights");

/* ****************************************************************************/
/* ********************************* SETUP ************************************/
/* ****************************************************************************/

void setup()
{
  Serial.begin(115200);

  dht1.begin();
  dht2.begin();
  // TESTING DHT
  h1 = dht1.readHumidity();
  t1 = dht1.readTemperature();
  Serial.println(h1);
  Serial.println(t1);
  h2 = dht2.readHumidity();
  t2 = dht2.readTemperature();
  Serial.println(h2);
  Serial.println(t2);

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Connecting to Wi-Fi");
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(300);
  }
  Serial.println();
  Serial.print("Connected with IP: ");
  Serial.println(WiFi.localIP());
  Serial.println();

  Serial.printf("Firebase Client v%s\n\n", FIREBASE_CLIENT_VERSION);

  /* Assign the api key (required) */
  config.api_key = API_KEY;

  /* Assign the user sign in credentials */
  auth.user.email = USER_EMAIL;
  auth.user.password = USER_PASSWORD;

  /* Assign the RTDB URL (required) */
  config.database_url = DATABASE_URL;

  /* Assign the callback function for the long running token generation task */
  config.token_status_callback = tokenStatusCallback; //see addons/TokenHelper.h

  Firebase.begin(&config, &auth);

  Firebase.reconnectWiFi(true);

  if (!Firebase.beginMultiPathStream(stream, parentPath)) {
      Serial.printf("stream begin error, %s\n\n", stream.errorReason().c_str());
  } else {
      Serial.printf("Stream begin successful");
  }
  humidifier.setFirebase();
  ventilator.setFirebase();
  heatmat.setFirebase();
  remote.setFirebase();
  lights.setFirebase();
  Firebase.setBoolAsync(database, "/greenhouse/standby", false);
  Firebase.setBoolAsync(database, "/greenhouse/cooling", false);
  Firebase.setMultiPathStreamCallback(stream, streamCallback, streamTimeoutCallback);
  timerHandler(2);
}

/* ****************************************************************************/
/* ********************************* LOOP *************************************/
/* ****************************************************************************/

void loop()
{
  currentTime = millis();

    if((currentTime - previousTimerL) > timerL) {
        Serial.println("time to check the remote and lights");
        previousTimerL = currentTime;
        timerHandler(2);
    } else {}

    if((currentTime - previousSensors) > timerSensors) {
        Serial.println("time to check the DHTs");
        previousSensors = currentTime;
        updateDHT();
    } else {}

    switch (state)
    {
    .....
    }
}

/* ****************************************************************************/
/* ******************************* FUNCTIONS *******************************/
/* ****************************************************************************/

void updateDHT(void)
{
    //get temperature and humidity
    Serial.println("Updating DHT22 data!");
    h1 = dht1.readHumidity();
    h2 = dht2.readHumidity();
    t1 = dht1.readTemperature();
    t2 = dht2.readTemperature();
   ...
}


void streamCallback(MultiPathStreamData stream)
{
    size_t numChild = sizeof(childPath) / sizeof(childPath[0]);
    
    for (size_t i = 0; i < numChild; i++)
    {
        if (stream.get(childPath[i]))
        {
        //Serial.printf("path: %s, event: %s, type: %s, value: %s%s", stream.dataPath.c_str(), stream.eventType.c_str(), stream.type.c_str(), stream.value.c_str(), i < numChild - 1 ? "\n" : "");
            String isOn = stream.value.c_str();
            switch(i)
            {
                case 0: // HEATMAT
                break;
                case 1: // HUMIDIFIER -> ENABLES THE VENTILATOR TOO
                break;

               ...

                case 18: //manual Lights mode
                break;
                default:
                break;
            }
        } else{}
    }
}

void streamTimeoutCallback(bool timeout)
{
  if (timeout)
    Serial.println("stream timeout, resuming...\n");
}
```

**Comment by mobizt** [comment]
It's not a library issue.  

There's nothing related between the libraries, no shared memory, static function and variable, everything is defined inside class.

This may be memory issue instead.

When you assign the callback function, the RTOS task for stream will be created with the stack memory reserved for specific amount.

If you call F**irebase.setMultiPathStreamCallback**, without providing the forth argument (**streamTaskStackSize**), the default stack size for stream task will set to 8192 k.

Your device may running low heap memory and some of your code included third party libs or core libs may not work properly or fail to allocate memory. 

You should debug and checking free memory.

**Comment by mobizt** [comment]
You should test with clean and simple code between Firebase and sensor libraries, without your class or object that consumed extra memory.

I recommend to use this [stream example](https://github.com/mobizt/Firebase-ESP32/blob/master/examples/DataChangesListener/Callback/Callback.ino) to test with sensor.

The multipath stream and stream operations are the same unless the multipath stream has the function to parse the JSON payload as stated in the example.
https://github.com/mobizt/Firebase-ESP32/blob/e73423a2de65d16bc09f012908e25a1a87d0b804/examples/DataChangesListener/MultiPath/MultiPath.ino#L132

**Comment by popeyaho001** [comment]
@fubl84 have you fix this, i had the same error. can not read from dht22 while using callback

**Comment by mobizt** [comment]
> @fubl84 have you fix this, i had the same error. can not read from dht22 while using callback

 If you ask my reply, there is nothing related.

Users should debug this themselves.

Stream function with callback creates the RTOS task on CPU core 1 with 8192 bytes reserved stack memory. Inside the task is infinite loop calling readStream with 3 ms delay, that's it.

You should debug your code for memory and timing and should use the sensor library properly. Or change the sensor library that dosn't use delay inside or something that waits for onewire, i2c interfaces.

The good sensor library must not use delay or blocking code to wait onewire or i2c bus to be ready which is the blocking process that affects other code to run properly.
