### ISSUE TITLE
Device creashes when calling Firebase.begin()

### ISSUE THREAD

**Issue by sapuz1508** [mobizt/Firebase-ESP32#20]
When i write the line `Firebase.begin("FIREBASE_ID", "SECRET")` it continues to crash with the log

`rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:10088
load:0x40080400,len:6380
entry 0x400806a4`

help pls!

**Comment by mobizt** [comment]
No special operation inside **Firebase.begin** to cause the error.  It's just to store credentials data in C and C++ basic string.

Try all of followings

* **Update your Arduino IDE.**
* **Update ESP32 Arduino Core SDK to version 1.0.2 (available from Boards Manager)**
* **Update Firebase ESP32 library (download v 3.1.0 directly from Github, delete the old one in Libraries folder and install the downloaded library)**

**Post your sketch here if still getting error.**

**Comment by sapuz1508** [comment]
Thx
