### ISSUE TITLE
I'm using ESP32 by sending data to firebase but it only works a few times.

### ISSUE THREAD

**Issue by keecook** [mobizt/Firebase-ESP32#229]
Whenever I scan my face through I send it to Firebase. I have tested it by scanning the face 2 times and it works fine. But when the 3rd time the ESP-32CAM reboots, the serial monitor says:

Item psram alloc failed. Size: 53824 x 2
23:11:37.662 -> matrix3dq item alloc failed.
23:11:37.662 -> Guru Meditation Error: Core 1 panic'ed (LoadProhibited). Exception was unhandled.
23:11:37.662 -> Core 1 register dump:
23:11:37.662 -> PC : 0x401a4ddc PS : 0x00060730 A0 : 0x801a0603 A1 : 0x3ffb1cd0
23:11:37.662 -> A2 : 0x00000001 A3 : 0x0000000 A4 : 0x00000003 A5 : 0x3ffde2d4
23:11:37.697 -> A6 : 0x0000001c A7 : 0x3ffde2a4 A8 : 0x3f5aa610 A9 : 0x3ffb1c50
23:11:37.697 -> A10 : 0x00000001 A11 : 0x0000001c A12 : 0x0000000 A13 : 0x3f5ab690
23:11:37.697 -> A14 : 0x00000002 A15 : 0x3f5ab730 SAR : 0x00000004 EXCCAUSE: 0x0000001c
23:11:37.697 -> EXCVADDR: 0x00000000 LBEG : 0x4008fad1 LEND : 0x4008fae1 LCOUNT : 0xfffffff8
23:11:37.697 ->
23:11:37.697 -> ELF file SHA256:0000000000000000
23:11:37.697 ->
23:11:37.697 -> Backtrace: 0x401a4ddc:0x3ffb1cd0 0x401a0600:0x3ffb1d20 0x40138498:0x3ffb1dd0 0x4013855d:0x3ffb1df0 0x400d2ca4:0x3ffb1e20 0x400d2b66:0x3ffb1e40 0x400d2bf8:0x3ffb1e90 0x400d2ce1:0x3ffb1eb0 0x400d2b66:0x3ffb1ed0 0x400d2bf8:0x3ffb1f20 0x400d2ce1:0x3ffb1f40 0x400d2b66:0x3ffb1f60 0x400ebb1d:0x3ffb1fb0 0x40092b9e: 0x3ffb1fd0
23:11:37.731 ->
23:11:37.731 -> Rebooting...
 
I have tested it without it sending data to firebase it can scan faces more than 2 times so i think it is sending data to firebase I've tried to fix this problem several times, but I haven't been able to fix it. please help me to solve this problem 

[I have attached a video](https://drive.google.com/file/d/1zyLaRyVNVP9BIPjSafOHEvInT8-S_u4M/view?usp=sharing)

**Comment by mobizt** [comment]
You have to debug your code.

Nothing is related to library issue.

I can't help anything as you skip all steps in issue templates that described required information for anyone can understand your problem.

**Comment by mobizt** [comment]
You should decode the stack with [this tool](https://github.com/me-no-dev/EspExceptionDecoder).
