### ISSUE TITLE
ESP is not able to read using getString function when using v3.11 onwards

### ISSUE THREAD

**Issue by Hassaan18** [mobizt/Firebase-ESP32#240]
Firebase read function works fine until v3.10.5 but 3.11 takes the database path as a constant template. Even doing so, it can write to the database using setString function but on reading, it's returning empty string.

**Comment by mobizt** [comment]
The library was updated. You should also update your code to pass String pointer to readString function.

**Comment by Hassaan18** [comment]
Yes, I'm passing that to the function. Please refer to the code below

```
  String tmp;
  String path = "/" + String(i);
  Firebase.setString(firebasedata, path, "XYZ");
  Firebase.getString(firebasedata, path, tmp);
```

**Comment by mobizt** [comment]
No, you can't pass as object like that in the new version because the library APIs changed for almost year. You should  pass the pointer of String e.g. &tmp.

**Comment by mobizt** [comment]
For example.

`Firebase.getString(firebasedata, path, &tmp);`

**Comment by mobizt** [comment]
You should update the library to latest version first.
