### ISSUE TITLE
Token error: code: -4, message: connection lost ISSUE NODEMCU ESP32-S

### ISSUE THREAD

**Issue by EvansQSMK** [mobizt/Firebase-ESP32#244]
ESP Model: NODEMCU ESP32-S V1.1
Hi! i have some troubles with my project.
I'm using the RTDB of Firebase, when i turn on the ESP i get this error message when i try to signup:
`Token info: type = id token, status = on request
Token info: type = id token, status = error
Token error: code: -4, message: connection lost`

It is interesting because this problem appears when the ESP is connected to the wifi of my school or the wifi of my mobile. But it works correctly when it is connected to my home wifi

**Comment by mobizt** [comment]
This is your WiFi problem and is not related to library.
