### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by chinhaka** [mobizt/Firebase-ESP32#278]
Hello, i have timeout issues of firebase. After when connection lost some time it shows timeout error.  Firebase stream is also not read5data after some time. (After 1 hour).

How can i initiate firebase and firebase stream again after connection lost or token expired or any error.

**Comment by mobizt** [comment]
Please follow the examples to use library correctly.
https://github.com/mobizt/Firebase-ESP32/tree/master/examples
