### ISSUE TITLE
Get return empty response after several calls

### ISSUE THREAD

**Issue by thecodingfrog** [mobizt/Firebase-ESP32#279]
Hello,

I'm experiencing troubles with this library but not sure if it's a library bug or if it is related to a memory problem.
I'm using a wt32 sc01 board based on an esp32.
I'm requesting data from a rtdb at periodic interval but after few minutes the response is getting wild. It looks like a memory problem but I don't know how to trace it.

**Comment by mobizt** [comment]
You should debug your code first which the library provides the examples with debugging ability which you should try.

You should manage your device memory well in critical memory situation in case you work with many libraries in your code.
