### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chinhaka** [mobizt/Firebase-ESP32#285]
Dear Mobizt,

Can you help me with the following. Since a few days I'm having problems with the Firebase connection to my esp32 dev kit. The esp32 establishes the code, but won't keep it running. After some time, it just says 'connection refused', or 'connection lost'. After that it says 'stream timeout'. I checked wifi status on when error occurred. Wifi status is connected in every time. Sometimes token refresh token automatically once or twice. After few hours on refreshing token get error. Never refresh the token. Is their any way to close the firebase connection and re initiate again when error occurs.? Firebase.reset() not works because callback function didn't stop after errors.

**Comment by mobizt** [comment]
Your problem may relate to out of memory condition which the internal SSL client may fail to do SSL handshake.

You should set the debug port in Arduino IDE and you will see this error from SSL client.
