### ISSUE TITLE
Issue with token requesting

### ISSUE THREAD

**Issue by Manuel-Savyak** [mobizt/Firebase-ESP32#298]
im trying to connect my esp32 to a firebase realtime database do send some variables and it keeps printing this in the serial monitor:
10:53:34.168 -> Token info: type = id token (GITKit token), status = on request
10:53:39.164 -> Token info: type = id token (GITKit token), status = error
10:53:39.164 -> Token error: code: -4, message: connection lost

**Comment by mobizt** [comment]
That is the network (WiFi) connection problem.

**Comment by Manuel-Savyak** [comment]
> That is the network (WiFi) connection problem.

i saw you solving a similar problem but i cant find the example the you said to use

**Comment by mobizt** [comment]
That is your network problem and you should fix it yourself.

**Comment by mobizt** [comment]
If you call `Firebase.reconnectWiFi(true)`, the library will reconnect your WIFi using the saved WiFi credentials in flash once your device was disconnected from WiFi.
