### ISSUE TITLE
 ESP8266WiFi.h: No such file or directory

### ISSUE THREAD

**Issue by nurullahozatak** [mobizt/Firebase-ESP32#311]
I have this issue I hope you can fix : Documents\Arduino\libraries\firebase-arduino-master\src\FirebaseHttpClient_Esp8266.cpp:8:10: fatal error: ESP8266WiFi.h: No such file or directory

And here is my code

#include <Arduino.h>
#include <WiFi.h>

#include <FirebaseESP32.h>

#define FIREBASE_HOST "aaaaaaaaaaaaaaaaaaa"
#define FIREBASE_AUTH "aaaaaaaaaaaaaaaa"

#define SENSOR_PIN 4   // Sensör için uyumlu pin atması
#define BUZZER_PIN 5   // Buzzer için uyumlu pin atması
#define RGB_LED_PIN 2   // RGB LED için uyumlu pin atması

const char* ssid = "aaaaaaaaaaa";
const char* password = "aaaaaaaaaa.";

bool doorStatus = false;

void setup() {
  Serial.begin(115200);                             //Seri iletişim hızı 9600 bps olarak ayarlanarak başlatılıyor.
  delay(1000);
  Serial.println("Wifi agina baglaniliyor");

  WiFi.mode(WIFI_MODE_STA);                       //ESP8266 istasyon moduna alınıyor. 
  WiFi.begin(ssid, password);                    //SSID ve şifre girilierek wifi başlatılıyor.

  //------- Wifi ağına bağlanıncaya kadar beklenilen kısım ------------
  while (WiFi.status() != WL_CONNECTED) 
  { 
    delay(500);                                 // Bu arada her 500 ms de bir seri ekrana yan yana noktalar yazdırılarak
    Serial.print(".");                          //görsellik sağlanıyor.
  }
  //-------------------------------------------------------------------

  Serial.println("");                           //Bir alt satıra geçiliyor.
  Serial.println("Bağlantı sağlandı...");       //seri ekrana bağlantının kurulduğu bilgisi gönderiliyor.

  Serial.print("Alınan IP addresi: ");          // kablosuz ağdan alınan IP adresi
  Serial.println(WiFi.localIP());               // kablosuz ağdan alınan IP adresi

  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH); // firabase i başlat

  // Pin modlarını ayarlama
  pinMode(SENSOR_PIN, INPUT);
  pinMode(BUZZER_PIN, OUTPUT);
  pinMode(RGB_LED_PIN, OUTPUT);
}

void loop() {
  // Kapı durumunu kontrol etme
  bool currentStatus = digitalRead(SENSOR_PIN);

  if (currentStatus != doorStatus) {
    doorStatus = currentStatus;

    if (doorStatus) {
      // Kapı açıldı
      Serial.println("Door opened");

      // Buzzer'ı çalma
      digitalWrite(BUZZER_PIN, HIGH);

      // RGB LED'i kırmızıya ayarlama
      analogWrite(RGB_LED_PIN, 255);

      // Firebase'e veri gönderme
      sendFirebaseData("Door opened!");
    } else {
      // Kapı kapandı
      Serial.println("Door closed");

      // Buzzer'ı kapatma
      digitalWrite(BUZZER_PIN, LOW);

      // RGB LED'i yeşile ayarlama
      analogWrite(RGB_LED_PIN, 0);

      // Firebase'e veri gönderme
      sendFirebaseData("Door closed.");
    }
  }

  delay(1000); // Sensörü her saniyede bir kontrol et
}

void sendFirebaseData(const char* message) {
  Firebase.pushString("doorStatus", message);
  Serial.println("Data sent to Firebase");
}

**Comment by mobizt** [comment]
It's not related what error you post. It's not this library error.
