### ISSUE TITLE
FCM API V1 always fail

### ISSUE THREAD

**Issue by armanArk** [mobizt/Firebase-ESP32#328]
**Just ask something**
Hello 
![Screenshot 2024-06-22 172815](https://github.com/mobizt/Firebase-ESP32/assets/173204025/3ba6ac3d-8820-45c3-895a-8cfb68522fb5)
Does this Lib support Firebase cloud messaging V1 ?
i test to send but always getting fail

**IDE and its version:**
 - Arduino, PlatformIO
 - Version [e.g. 1.8.9]

**ESP32 Arduino Core SDK version**
 - Version [e.g. 2.0.2]

**Additional context**

**Comment by mobizt** [comment]
Read the documentation.

**Comment by armanArk** [comment]
![Screenshot 2024-06-22 220655](https://github.com/mobizt/Firebase-ESP32/assets/173204025/71caba53-aaad-4544-a570-05c82d5b0214)
i have running with FirebaseEsp client https://github.com/mobizt/Firebase-ESP-Client.git still get -108 error code, 
did you have sugestion?

**Comment by armanArk** [comment]
![Screenshot 2024-06-22 172815](https://github.com/mobizt/Firebase-ESP32/assets/173204025/bbe6b6c5-9406-4320-a259-c0305fbf834b)
i have running with your FirebaseEspClient https://github.com/mobizt/Firebase-ESP-Client.git but still get -108 error code, 
did you have any suggestion?
