### ISSUE TITLE
upgrade from 4.3.8 to 4.4.14 results in compiler error usining RTDB

### ISSUE THREAD

**Issue by JoergTiedemann** [mobizt/Firebase-ESP32#330]
Hi 
I upgrade from version 4.3.8 to version 4.4.14 on platformio.
I use the following comand to write a JSON object into Realtime Database:

Firebase.RTDB.setJSON(&fbdo, TempParentPath.c_str(), &jsonTemp))

If i compile i got the error message
src/FirebaseManager.cpp:973:21: error: 'FB_RTDB FirebaseESP32::RTDB' is private within this context

Seems that i haven't use the right definitions in FirebaseFS.h or what is wrong ?
I see in Firebase.h in line 94 that FIREBASE_ESP CLIENT is not defined. Is this the reason or what I have to do to upgrade from 4.3.8 to latest version ?
Thanks for any Help in advance

**Comment by mobizt** [comment]
https://github.com/mobizt/Firebase-ESP32?tab=readme-ov-file#we-have-moved-to-the-new-library

For the proper usage, check the library examples in the examples folder.
