### ISSUE TITLE
RAM usage improvement?

### ISSUE THREAD

**Issue by mrdc** [mobizt/Firebase-ESP32#34]
Hello,

I'm using the Firebase library in my project on ESP32 Wroom, it doesn't have additional PSRAM, so there is not too much free RAM to use. 
What I've noticed is that my ESP32 Free Heap is 51292 after boot. I've compared Free Heap to the library IOXhop_FirebaseESP32 which gives me ~94700 after boot with the same code as used with your library.
Do you think there is space for RAM usage improvement?

**Comment by mobizt** [comment]
It's strange and unbelievable.
For example if you use two FirebaseData object, the free heap is about 160-170k.
Something wrong with your code? 
You should share your code.

**Comment by mrdc** [comment]
I'm using BLE - it uses a lot of RAM.

**Comment by mobizt** [comment]
You should not use BLE together with WiFi because it use the same radio.
You need to disable BLE and reboot to use WiFi only get more free heap.

**Comment by mrdc** [comment]
BTW it's possible to use at the same time even if it uses the same radio.

**Comment by mobizt** [comment]
No

**Comment by mrdc** [comment]
I know about mbed memory usage. In may case it works OK.

**Comment by mobizt** [comment]
Are you sure for SSL/TLS?

**Comment by mrdc** [comment]
How can I check it? What I see is that ESP32 connects to 443 port.

**Comment by mobizt** [comment]
You can test to use WiFiClientSecure to connect to some server  via ssl (use https in server url or host).  It uses a lot of ram in SSL handshake and decrypt/encrypt exchanged data.  

I'm not recommended to use both BLE and WiFi at the same time for high WiFi priority tasks as stream which it needs connection to stay alive.
