### ISSUE TITLE
help:with accessing particular json path data. 

### ISSUE THREAD

**Issue by vamsikrishnaA9** [mobizt/Firebase-ESP32#36]
hi there,
thanks for the library.
i need to access the particular json key data.
is there any way to access the particular key data with out using json.getiterator() function, because we need to put the particular array value to get the key and data.
thank you

**Comment by mobizt** [comment]
Make sure you update library to the latest version. I recommended to download from git version.

You can use **FirebaseJsonData** to get the parse result like this.

Please refer to the doc [here](https://github.com/mobizt/Firebase-ESP32#parse-create-and-edit-json-objects) 
```C++

//Declare FirebaseJsonData object to get the parse result, similar to FirebaseData object
FirebaseJsonData jsonData;

json.get(jsonData, "unit/temp2");

if (jsonData.success)
{
  //Print type of parsed data e.g string, int, double, bool, object, array, null and undefined
  Serial.println(jsonData.type);
  //Print its content e.g.string, int, double, bool whereas object, array and null also can access as string
  Serial.println(jsonData.stringValue);
  //Serial.println(jsonData.intValue);
  //Serial.println(jsonData.boolValue);
  //Serial.println(jsonData.doubleValue);
}

```

**Comment by vamsikrishnaA9** [comment]
It works . Thank you
