### ISSUE TITLE
HELP: how to check the internet status thorugh firebase esp32 lib

### ISSUE THREAD

**Issue by vamsikrishnaA9** [mobizt/Firebase-ESP32#37]
hi there,
i need to check the live internet status. I ve gone through the library. I found httpCode and httpConnected () functions are for checking status server connection.
But i failed to get the live internet check through those functions.
Is there any particular function availble to know the internet check?
Thank you.

**Comment by mobizt** [comment]
For internet status, you need to check by yourself via ping or create http request to some sever e.g. google.com. 

The httpCode value changes upon the Firebase operation (get, set, push, delete, update and stream).

**Comment by vamsikrishnaA9** [comment]
Yeah got it. thanks mate
