### ISSUE TITLE
Firebase.setInt

### ISSUE THREAD

**Issue by lem0928** [mobizt/Firebase-ESP32#39]
Hey guys.

So I just watched IoT Home Automation Using Firebase in youtube uploaded by RoboShala. 

My problem is that I'm using esp32 and he used esp8266. I installed the esp32 firebase in arduino library manager, copied his code. 

Only changed the include header file from firebaseESP8266.h to firebaseESP32.h to suit my devboard. 

Then when I compile the code, the Firebase.setInt("S1",0) line gets the message: 

'No matching function for call to FirebaseESP32:setInt(const char[3], int). '

I fixed that. I'd be happy for an explanation though, because I'm not sure how I did it. 

I'm also having problems with the line

if(Firebase.failed()) 

Arduino tells an error that says: FirebaseESP32 has no member named failed.

how should I fix that? I want to achieve the same results that the youtube video is doing.

**Comment by mobizt** [comment]
The library provides different APIs, please see these [examples](https://github.com/mobizt/Firebase-ESP32/tree/master/examples). I provide a lot of info in doc at the [main page](https://github.com/mobizt/Firebase-ESP32).
