### ISSUE TITLE
Firebase.get function is bugged I think?

### ISSUE THREAD

**Issue by lem0928** [mobizt/Firebase-ESP32#43]
I am using your version 3.5.5 of firebaseESP32. 
Whenever I try to use the get function,
example:
double myValue = 3.1415926;
Firebase.setDouble(dataObj,path,myValue);
double getStatus = Firebase.getDouble(dataObj,path);
Serial.print(getStatus);
.
the getStatus printed is always in the value of 1 when in this case it should be 3.1415926.
What should I do? Thanks!

**Comment by mobizt** [comment]
Read the example, almost Firebase calls return true for success and false for failed. You need to get data from FirebaseData object as dataobj.doubleValue.
