### ISSUE TITLE
HELP: returning  Json data type while posting boolean from esp32

### ISSUE THREAD

**Issue by vamsikrishnaA9** [mobizt/Firebase-ESP32#45]
Hi,
I am posting boolean/int/string/float from esp32 using "set()" functions, but the stream data always returns json type instead of bool/int/string/float. How can i get the exact data type which i have posted from esp32 hardware ?  
Thanks

**Comment by mobizt** [comment]
Please show your code.

**Comment by mobizt** [comment]
You need to show your working code for me to check and test.

**Comment by mobizt** [comment]
If you're not provide any code, I'm sorry to delete the issue.
