### ISSUE TITLE
Stream stops working when delays are used

### ISSUE THREAD

**Issue by itsmebasti** [mobizt/Firebase-ESP32#54]
1. Run the stream_loop example.
2. Change the loop method like this:
   - Remove the database update part
   - Add a `delay(1000);` to the bottom of the loop method.

3. Rerun it and apply changes to the database manually.

The changes will never be noticed by the `readStream `method. The initial state is not even queried on the first loop.

Arduino IDE 1.8.10
ESP32 Dev Module

**Comment by mobizt** [comment]
That is normal behavior not for this library.

As in web server library, you need to allow stream to run freely without block code e.g. delay or some time consuming tasks.

You can set stream callback function to get the stream changes which stream call will run forever internally in RTOS task.
