### ISSUE TITLE
HELP .....

### ISSUE THREAD

**Issue by noonmasho** [mobizt/Firebase-ESP32#63]
Hi, I would like to thank you for actively maintaining this library. I need one help. I have gone through all the documentation. I'm not able to use a character array in json.set  function. I need to send the character array of 7 bytes ( made of numbers) to RTDB as json . Please guide me for the same.

Thanking you in advance, Thank you, Thank you........

**Comment by mobizt** [comment]
You need to cast char array to constant char array, here the example

```C++
   FirebaseJsonArray arr;

  char str[] = {'a', 'b', 'c', 'd', 'e', 'f', 'g','\0'};
  
  arr.set("/[0]/[1]", (const char*) str);

  Firebase.setArray(firebaseData1, "test1", arr);

  arr.clear();

  arr.set(0, (const char *)str);

  Firebase.setArray(firebaseData1, "test2", arr);
```
