### ISSUE TITLE
how to read a Jason? 

### ISSUE THREAD

**Issue by biswajitjei02** [mobizt/Firebase-ESP32#78]
![image](https://user-images.githubusercontent.com/38404689/84386015-365ff780-ac0e-11ea-9293-9fe1a1412c31.png)

here  want a Jason like this 
**{newvalue: 32, value: 1,value1: "no"}**

**Comment by mobizt** [comment]
If you want to get the data at the root of your database, use **Firebase.getJSON** with the path parameter "/"

```C++
  Firebase.getJSON(firebaseData, "/");

  FirebaseJson &json = firebaseData.jsonObject();

  FirebaseJsonData parseRsult;

  json.get(parseRsult, "/newvalue");

  if (parseRsult.success)
  {
    Serial.println(parseRsult.intValue);
  }

  json.get(parseRsult, "/value");

  if (parseRsult.success)
  {
    Serial.println(parseRsult.intValue);
  }

  json.get(parseRsult, "/value1");

  if (parseRsult.success)
  {
    Serial.println(parseRsult.stringValue);
  }
```

**For more usage of the FirebaseJson object**

 https://github.com/mobizt/Firebase-ESP32#parse-create-and-edit-json-objects
https://github.com/mobizt/Firebase-ESP32/blob/master/examples/jsonObject/jsonObject.ino
https://github.com/mobizt/Firebase-ESP32/tree/master/examples/FirebaseJson/examples

**Comment by biswajitjei02** [comment]
i want to store as a single Json a ,how it can be done ?

**Comment by mobizt** [comment]
I don't understand what you mean.

**Comment by mobizt** [comment]
Please read the Readme doc or start with the examples.

**Comment by biswajitjei02** [comment]
this type of out put i want 
//Declare FirebaseJson object (global or local)
FirebaseJson json;

//Add name with value Living Room to JSON object
json.add("name", "Living Room");

//Add temp1 with value 120 and temp1 with 40 to JSON object
//Note: temp2 is not the child of temp1 as in previous version.
json.add("temp1", 120).add("temp2", 40);

//Add nested child contents directly
json.set("unit/temp1", "Farenheit");
json.set("unit/temp2", "Celcius");

//To print out as prettify string
String jsonStr;
json.toString(jsonStr, true);
Serial.println(jsonStr);

/*
This is the result of the above code

{
    "name": "Living Room",
    "temp1": 120,
    "temp2": 40,
    "unit": {
        "temp1": "Farenheit",
        "temp2": "Celcius"
    }
}
