### ISSUE TITLE
Can it be used for Firestore too?

### ISSUE THREAD

**Issue by mbariola** [mobizt/Firebase-ESP32#84]
Hi @mobizt , 

thanks for this library, I am trying to interface an old web hobby project of mine which uses firestore instead of firebase. Can this library be somehow used for firestore, or do you have any plans to create a firestore version?

thanks

**Comment by mobizt** [comment]
It can't use with Firestore now.
But I have planned but can't implement due to gRPC is not support.  I choose gRPC instead of REST because of real-time feature of Firestore is only available in gRPC.

**Comment by mbariola** [comment]
Understood. Thanks for the quick answer!
