### ISSUE TITLE
Arduino\libraries\Firebase_Arduino_based_on_WiFiNINA\src/Firebase_Arduino_WiFiNINA.h:51:26: fatal error: avr/pgmspace.h: No such file or directoryBUG

### ISSUE THREAD

**Issue by kenken64** [mobizt/Firebase-ESP32#87]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**IDE and its version:**
 - Arduino, PlatformIO
 - Version [e.g. 1.8.9]

**ESP8266 Arduino Core SDK version**
 - Version [e.g. 2.5.1]

**Additional context**

**Comment by mobizt** [comment]
You are using the unsupported or incompatible device with this library.

Please read the readme and check your device (board) that supported by the library.

**Comment by mobizt** [comment]
This is for ESP32 platform. The error you mentioned is for AVR/ARM platforms.
