### ISSUE TITLE
Error firebase esp32

### ISSUE THREAD

**Issue by MaxESP** [mobizt/Firebase-ESP32#9]
Arduino\libraries\Firebase-ESP32-master/FirebaseESP32.h:460:8: error: 'vector' in namespace 'std' does not name a template type

**Comment by mobizt** [comment]
Sorry for the error, include vector at the top of FirebaseESP32.h will help.
`#include <vector>`

I recently [fixed.](https://github.com/mobizt/Firebase-ESP32/commit/4b91b600a0acb9b5cae31a839cfef93e1c4bef99) Please update library or download new [FirebaseESP32.h](https://github.com/mobizt/Firebase-ESP32/blob/master/src/FirebaseESP32.h)

**Comment by MaxESP** [comment]
Thank you very much for your up date i have find one witch work

#include <IOXhop_FirebaseESP32.h>


M khales naim

________________________________
De : mobizt <notifications@github.com>
Envoyé : vendredi 8 mars 2019 13:48
À : mobizt/Firebase-ESP32
Cc : MaxESP; Author
Objet : Re: [mobizt/Firebase-ESP32] Error firebase esp32 (#9)


Sorry for the error, include vector at the top of FirebaseESP32.h will help.
#include <vector>

I recently fixed.<https://github.com/mobizt/Firebase-ESP32/commit/4b91b600a0acb9b5cae31a839cfef93e1c4bef99> Please update library or download new FirebaseESP32.h<https://github.com/mobizt/Firebase-ESP32/blob/master/src/FirebaseESP32.h>
