### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by pondkule** [mobizt/Firebase-ESP32#97]
I am doing project in ESP32 SIM800L using Airtel Sim internet.This project work with Blynk.I can use sim internet to run blynk application.
but when i try to use sim internet to conncet firebase its getting error connection lost but in same code if i use Mobile hotspot program works.
Is there any additional setting to use firbase for sim internet?

**Comment by mobizt** [comment]
The library is only for ESP32, no external UART network bridge devices or AT firmware supported.
