### ISSUE TITLE
low frequency of updates 

### ISSUE THREAD

**Issue by Dzunior** [mobizt/Firebase-ESP32#99]
Hi,
I'm trying examples to update fields - it works fine but having a problem to update it more frequently. Currently, I'm able to update a field around once/second and would like to update it 3-4 times per second (to be more realtime). Any thoughts how this can be improved?

Thanks,
Dzunior

**Comment by mobizt** [comment]
Thanks for inform this issue.

It's a slow connection bug which found in v 3.7.6 to 3.7.8.

Now this issue was fixed in v 3.7.9.   Please update from GitHub download (if it not available in library manager).
